# docker/docker-compose.yml
version: '3'

networks:
  awesomeProjectAPINetworks:

services:
  awesome-project-golang:
    container_name: awesome-project-golang
    build:
      context: ./Dockerfiles/awesomeProjectGolang
      args:
        UID: ${UID}
        GID: ${GID}
        APP_ENV: ${APP_ENV}
    ports:
      - '80:80'
    volumes:
      - ./:/app
    networks:
      - awesomeProjectAPINetworks