# docker/docker-compose.yml
version: '3'

networks:
  APINetworks:

services:
  golang-tty:
    container_name: golang-tty
    build:
      context: Dockerfiles/golangTTY
      args:
        UID: ${UID}
        GID: ${GID}
        APP_ENV: ${APP_ENV}
    stdin_open: true
    tty: true
    volumes:
      - ./src:/go/src
      - ./bin:/go/bin
      - ./pkg:/go/pkg
      - ./script:/root
    networks:
      - APINetworks

  golang:
    container_name: golang
    build:
      context: Dockerfiles/golang
      args:
        UID: ${UID}
        GID: ${GID}
        APP_ENV: ${APP_ENV}
    ports:
      - '8001:8080'
    volumes:
      - ./src:/go/src
      - ./bin:/go/bin
      - ./pkg:/go/pkg
      - ./script:/root
    networks:
      - APINetworks

